package org.tempuri;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-07-08T21:31:24.059+03:00
 * Generated source version: 3.4.2
 *
 */
@WebServiceClient(name = "SigSirketWS",
                  wsdlLocation = "classpath:wsdl/tobb.wsdl",
                  targetNamespace = "http://tempuri.org/")
public class SigSirketWS extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "SigSirketWS");
    public final static QName SigSirketWSSoap = new QName("http://tempuri.org/", "SigSirketWSSoap");
    public final static QName SigSirketWSSoap12 = new QName("http://tempuri.org/", "SigSirketWSSoap12");
    static {
        URL url = SigSirketWS.class.getClassLoader().getResource("wsdl/tobb.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(SigSirketWS.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/tobb.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SigSirketWS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SigSirketWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SigSirketWS() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SigSirketWS(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SigSirketWS(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SigSirketWS(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SigSirketWSSoap
     */
    @WebEndpoint(name = "SigSirketWSSoap")
    public SigSirketWSSoap getSigSirketWSSoap() {
        return super.getPort(SigSirketWSSoap, SigSirketWSSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SigSirketWSSoap
     */
    @WebEndpoint(name = "SigSirketWSSoap")
    public SigSirketWSSoap getSigSirketWSSoap(WebServiceFeature... features) {
        return super.getPort(SigSirketWSSoap, SigSirketWSSoap.class, features);
    }


    /**
     *
     * @return
     *     returns SigSirketWSSoap
     */
    @WebEndpoint(name = "SigSirketWSSoap12")
    public SigSirketWSSoap getSigSirketWSSoap12() {
        return super.getPort(SigSirketWSSoap12, SigSirketWSSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SigSirketWSSoap
     */
    @WebEndpoint(name = "SigSirketWSSoap12")
    public SigSirketWSSoap getSigSirketWSSoap12(WebServiceFeature... features) {
        return super.getPort(SigSirketWSSoap12, SigSirketWSSoap.class, features);
    }

}
